before_script:
  - bash ./ci/install.sh


variables:
  MYSQL_DATABASE: homestead_testing
  MYSQL_ROOT_PASSWORD: secret

phpunit:php7.0:mysql5.7:
  image: php:7.0
  services:
    - mysql:5.7
  script:
    - php vendor/bin/phpunit --colors