language: php

php:
  - 7.0

sudo: false

env:
  global:
    - DB_HOST=localhost
    - DB_CONNECTION=mysql
    - DB_DATABASE=homestead
    - DB_USERNAME=root
    - DB_PASSWORD=

install:
  - mysql -e 'create database homestead;'
  - travis_retry composer install --no-interaction --prefer-source  
  - npm install -g npm@2
  - travis_retry npm install  

before_script:
  - cp config/env/.env.testing .env
  - travis_retry php artisan vendor:publish
  - travis_retry gulp --production
  - php artisan key:generate
  - php artisan migrate
  - php artisan db:seed

script:
  - vendor/bin/phpunit --coverage-clover build/logs/clover.xml;

after_script:
  - if [ "$TRAVIS_PHP_VERSION" == "5.5.9" ] || [ "$TRAVIS_PHP_VERSION" == "5.5" ] || [ "$TRAVIS_PHP_VERSION" == "5.6" ]; then wget https://scrutinizer-ci.com/ocular.phar; fi
  - if [ "$TRAVIS_PHP_VERSION" == "5.5.9" ] || [ "$TRAVIS_PHP_VERSION" == "5.5" ] || [ "$TRAVIS_PHP_VERSION" == "5.6" ]; then php ocular.phar code-coverage:upload --format=php-clover build/logs/clover.xml; fi
